export { default as Home } from './Home'
export { default as Rate } from './Rate'
export { default as Settings } from './Settings'
export { default as Connect } from './Connect'
export { default as Play, Drive, Beep } from './Play'
export { default as Discover, CodeLab } from './Discover'
export { Lessons, GetStarted } from './Learn'
export { default as Lab } from './Lab'
