export { Home } from './Home'
export { Rate } from './Rate'
export { Settings } from './Settings'
export { Play } from './Play'
export { Discover } from './Discover'
export { Learn, GetStarted } from './Learn'
export { Lab } from './Lab'
