#!/usr/bin/env bash

IMAGE_NAME=$(grep IMAGE_NAME .env.Docker | xargs)
IMAGE_NAME=${IMAGE_NAME#*=}

# Building the dockerfile with arguments passed
docker build \
    --build-arg BUILD_TOOLS_VERSION='25.0.2' \
    --build-arg ANDRIOD_VERSION='android-25' \
    --build-arg ANRIOD_SYSTEM_ARCH='x86_64' \
    --build-arg DEFAULT_DEVICE_NAME="Nexus 5" \
    -t $IMAGE_NAME .